#!/bin/bash
export ANDROID_FOLDER=/home/syukri/android/slimbean_4.3/

ShowMenu () {
clear
echo "=== LG Optimus 4X HD boot.img Creator (FOR NOW ONLY STOCK IS USABLE, ME LAZY)"
echo "=== by gingerboy92"
echo 
echo "- Ramdisk Selection"
echo
echo "- Please choose the appropriate rom type for your kernel:"
echo " "
echo " [1] JB v4.1.x - STOCK- LG (All Stock-based ROMS)"
echo " "
echo " [2] JB v4.1.x - MIUI - LG"
echo " "
echo " [3] JB v4.2.x - CM - LG"
echo " "
echo " [4] JB v4.3.x - CM - LG"
echo " "
echo " [x] Exit"
echo " "
}

while [ 1 ]
do
ShowMenu
read CHOICE
case "$CHOICE" in

###################################################################################################################
###################################################################################################################

"1")
echo " "
echo "Building boot.img for LG O4X Stock 4.1.2"
echo " "

echo "Cleaning possible previous remains"
rm -f build/initial/kernel
rm -f build/initial/boot.img-ramdisk.cpio.gz

echo "Copying kernel to build/initial"
cp $ANDROID_FOLDER/out/target/product/p880/kernel build/initial/
cp /home/syukri/modification/build/4.1.x-stock/ramdisk-optimus_prime/boot.img-ramdisk.cpio.gz build/initial/


if [[ -e build/initial/kernel ]]; then 
   echo "kernel found"
   clear
else
  echo "No kernel found in build/initial/, exiting"
   exit
fi;

if [[ -e build/initial/boot.img-ramdisk.cpio.gz ]]; then 
   echo "Ramdisk found"
   clear
else
  echo "No ramdisk found in build/initial/, exiting"
   exit
fi;

cd build/initial

echo "Packing boot.img"
../mkbootimg --kernel kernel --ramdisk boot.img-ramdisk.cpio.gz --cmdline ../cmdline.txt   --pagesize 2048 --base 0x10000000 --ramdiskaddr 0x11000000  -o boot.img

echo "Cleaning left overs"
rm -f kernel
rm -f boot.img-ramdisk.cpio.gz

echo "Moving boot.img to build/output/boot.img"
mv -f boot.img ../output/boot.img

cd ..

echo " "
echo " "
echo " "
echo "boot.img created for LG O4X Stock 4.1.2"
exit
;;

#################################################################################################################
#################################################################################################################

"2")
echo " "
echo "Building boot.img for LG O4X miui 4.1.2"
echo " "

echo "Cleaning possible previous remains"
rm -f build/initial/kernel
rm -f build/initial/boot.img-ramdisk.cpio.gz

echo "Copying kernel to build/initial"
cp $ANDROID_FOLDER/out/target/product/p880/kernel build/initial/
cp /home/syukri/modification/build/4.1.x-miui/ramdisk-optimus_prime/boot.img-ramdisk.cpio.gz build/initial/


if [[ -e build/initial/kernel ]]; then 
   echo "kernel found"
   clear
else
  echo "No kernel found in build/initial/, exiting"
   exit
fi;

if [[ -e build/initial/boot.img-ramdisk.cpio.gz ]]; then 
   echo "Ramdisk found"
   clear
else
  echo "No ramdisk found in build/initial/, exiting"
   exit
fi;

cd build/initial

echo "Packing boot.img"
../mkbootimg --kernel kernel --ramdisk boot.img-ramdisk.cpio.gz --cmdline ../cmdline.txt   --pagesize 2048 --base 0x10000000 --ramdiskaddr 0x11000000  -o boot.img

echo "Cleaning left overs"
rm -f kernel
rm -f boot.img-ramdisk.cpio.gz

echo "Moving boot.img to build/output/boot.img"
mv -f boot.img ../output/boot.img

cd ..

echo " "
echo " "
echo " "
echo "boot.img created for LG O4X miui 4.1.2"
exit
;;

#################################################################################################################
#################################################################################################################

"3")
echo "4.2.2 Selected, this is the default for now until i start building from 4.3 sources,
so all i will do is to copy the boot.img to output file"
echo ""
echo "Deleting old boot.img"
echo ""
if [[ -e build/output/boot.img ]]; then
  rm build/output/boot.img
fi
echo ""
echo "Copying new boot.img to output"
cp $ANDROID_FOLDER/out/target/product/p880/boot.img build/output/
echo "Should be done, right?"
exit
;;

#################################################################################################################
#################################################################################################################

#################################################################################################################
#################################################################################################################

"4")
echo "4.3 Selected, this is the default for now until i start building from 4.3+++ sources,
so all i will do is to copy the boot.img to output file"
echo ""
echo "Deleting old boot.img"
echo ""
if [[ -e build/output/boot.img ]]; then
  rm build/output/boot.img
fi
echo ""
echo "Copying new boot.img to output"
cp $ANDROID_FOLDER/out/target/product/p880/boot.img build/output/
echo "Should be done, right?"
exit
;;

#################################################################################################################
#################################################################################################################

"x")
exit
;;


esac

done
exit



